version: '3.8'
services:
  hitloop-docs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - .:/app

  hitloop-webserver:
    build:
      context: ./Webserver
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./Webserver:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
