version: '3.8'
services:
  docs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  webserver:
    build:
      context: ./Webserver
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./Webserver:/app
    environment:
      - FLASK_ENV=development