#ifndef CONFIG_H
#define CONFIG_H

#define POST_ENDPOINT "/data"
#define DEFAULT_PORT 5000

#define SCANNER_NAME "Scanner"
#define BEACON_NAME_PREFIX "HitloopBeacon"
#define BLE_SCAN_INTERVAL 100
#define BLE_SCAN_WINDOW 99
#define WIFI_CONNECT_DELAY 500
#define WIFI_SEND_DELAY 3000
#define SERIAL_BAUD_RATE 115200
#define SETUP_DELAY 1000
#define SCAN_TIME 10

#define BOOT_BUTTON_PIN 9

#define IMU_UPDATE_INTERVAL_MS 10
#define NUM_ANGLE_SAMPLES 10

#define LED_PIN D1
#define LED_COUNT 6

#endif

